stages:
  - build
  - deploy

startEC2_job:
  stage: .pre
  tags:
    - runner-manager   
  script:
    - python3 /home/gitlab-runner/start_stop_ec2.py START $EC2_INSTANCE_ID

build_job:
  stage: build
  tags:
    - dip-group-runner 
  script:
    - npm install --force
    - npm run build
  only:
    - master

deploy_job:
  stage: deploy
    tags:
    - dip-group-runner 
  script:
    - npm install --force
    - npm run build
    - mv ./build ./public

stopEC2_job:
  stage: .post
  tags:
    - runner-manager
  script:
    - python3 /home/gitlab-runner/start_stop_ec2.py STOP $EC2_INSTANCE_ID
  dependencies: [] # Skip artifacts download
  when: always